### ISSUE TITLE
Remove DEPLOY_SSH_KEY

### ISSUE THREAD

**Issue by albertvillanova** [albertvillanova/albertvillanova.github.io#4]
Action [peaceiris/actions-gh-pages@v3](https://github.com/marketplace/actions/github-pages-action) ([repo](https://github.com/peaceiris/actions-gh-pages)) now accepts GITHUB_TOKEN. 

Use GITHUB_TOKEN:
```yaml
github_token: ${{ secrets.GITHUB_TOKEN }}
```
instead of SSH_DEPLOY_KEY:
```yaml
deploy_key: ${{ secrets.SSH_DEPLOY_KEY }}
```

Workflow step should be: [link](https://github.com/marketplace/actions/github-pages-action#%EF%B8%8F-set-runners-access-token-github_token)
```yaml
    - name: Deploy
      if: github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.SSH_DEPLOY_KEY }}
        publish_dir: ./_site
```

## Reason

The creation of a GITHUB_TOKEN is done automatically by GitHub during the action and, contrary to SSH_DEPLOY_KEY, does not require any preliminary setup by the user. Currently, in the setup process, the user is required to create the SSH Deploy Key and the corresponding associated repository secret in advance.
